### ISSUE TITLE
.NET Core 2 support

### ISSUE THREAD

**Issue by vludax** [cake-contrib/Cake.Azure#10]
We've been using Cake.Azure for a few months now in multiple projects with great success. Thanks again for the project!

We wanted to add another step to our build script to run npm build with Cake.Npm (https://github.com/cake-contrib/Cake.Npm). That addin only targets netstandard 2.0. We were able to run Cake using dotnet, but unfortunately Cake.Azure doesn't support netstandard.

Would you mind adding support for netstandard 2.0? Thanks!

**Comment by gep13** [comment]
This has been addressed in this PR: https://github.com/cake-contrib/Cake.Azure/pull/13
