### ISSUE TITLE
Setup build and publishing using Cake.Recipe

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Azure#14]

**Comment by gep13** [comment]
@zbeer the initial stab at getting this working is complete.  A working build is here:

https://ci.appveyor.com/project/cakecontrib/cake-azure/builds/30294715

I have another couple of things to check over, but that will have to wait until tomorrow.

Any chance you can take the nupkg from here:

https://ci.appveyor.com/project/cakecontrib/cake-azure/builds/30294715/artifacts

For a spin to see if it is working as you would expect it to?

**Comment by zbeer** [comment]
@gep13:  Awesome!  Yessir, I'm happy to do so.

**Comment by zbeer** [comment]
@gep13:  Looks good to me!

**Comment by gep13** [comment]
@zbeer sweet!  There are a couple of small things that I want to check on, but aside from those, I will get this published as soon as possible.

**Comment by zbeer** [comment]
@gep13:  Just checking in - anything I can do to assist you?

**Comment by gep13** [comment]
@zbeer please accept my apologies for not getting back to you about this.  This sort of slipped through the cracks.  I am taking a look at this just now, and hopefully I will get 0.4.0 published tonight.  Thanks

**Comment by gep13** [comment]
@zbeer this has been published to NuGet here:

https://www.nuget.org/packages/Cake.Azure/0.4.0

And notifications were sent out to Twitter:

https://twitter.com/cakecontrib/status/1232478207732940800

and to Gitter:

https://gitter.im/cake-contrib/Lobby?at=5e55ca669aeef652321b55d5

I have also just invited you to becomes an owner of the Cake.Azure package on NuGet.org.

Are we in a position to unlist your Cake.AzureZ package?

Did I get you invited to the Cake-Contrib Slack Team?  Apologies if I didn't.

**Comment by zbeer** [comment]
@gep13: No worries, I appreciate you circling back and knocking it out!

I accepted the ownership request of Cake.Azure on NuGet.org; Cake.AzureZ has been unlisted.

You mentioned the Cake-Contrib Slack team, but I have not received an invite.

Thanks again for your help!

**Comment by gep13** [comment]
@zbeer can you let me know the best email address to send a Slack invitation to?

**Comment by zbeer** [comment]
@gep13:  Sent you a DM on Twitter!
