### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Azure#2]
Great work on getting this addin created!

This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#290

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by DixonDs** [comment]
@gep13 I have an issue which is still to be resolved before adding the addin to the website. It is connected to https://github.com/cake-build/cake/issues/1569 , ideally I would like to have it resolved in core Cake and not thinking of workarounds in my addin like using ILMerge

**Comment by gep13** [comment]
@DixonDs that is not a small issue to correct, so it is unlikely to be fixed in the short term.  While not ideal, the best course of action would be to use something like ILMerge'ing to workaround the issue.
