### ISSUE TITLE
Adding  #addin "Cake.Azure" alone is not enough

### ISSUE THREAD

**Issue by colindooley11** [cake-contrib/Cake.Azure#6]
Hi,  
I know I must be being completely stupid but what else do I have to add to get this working
There appear to be some types in Namespaces I cant find anywhere (ServiceCredentials for example - in Microsoft.Rest) 

Actually looking at source, ServiceClientCredentials needed by credentials is abstract and needs an impl. 
Ah well.

**Comment by DixonDs** [comment]
I've just executed the following script and it works fine for me:
```
#addin "Cake.Azure"

Task("Test")
    .Does(() =>
{
    var credentials = AzureLogin("<tenantId>", "<applicationId>", "<key>");
    EnsureAzureResourceGroupExists(credentials, "<subscriptionId>", "caketest", "northeurope");
})

RunTarget("Test");
```

Let me know if it helps
