### ISSUE TITLE
Recommended changes resulting from automated audit

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.Azure#7]
We performed an automated audit of your Cake addin and found that it does not follow all the best practices.

We encourage you to make the following modifications:

- [x] You are currently referencing Cake.Core 0.22.2. Please upgrade to 0.28.0
- [x] The Cake.Core reference should be private. Specifically, your addin's `.csproj` should have a line similar to this: `<PackageReference Include="Cake.Core" Version="0.28.0" PrivateAssets="All" />`
- [x] Your addin should target netstandard2.0. Please note that there is no need to multi-target, netstandard2.0 is sufficient.

Apologies if this is already being worked on, or if there are existing open issues, this issue was created based on what is currently published for this package on NuGet.org and in the project on github.

**Comment by vludax** [comment]
Now that the first item is done and the `Cake.Core` 0.28.0 is referenced, unfortunately I still can't debug a Cake script in VS code. The following exception is thrown:

> Error: Cake.Core.CakeException: Failed to install addin 'Cake.Azure'.
>    at Cake.Core.Scripting.ScriptProcessor.InstallAddins(IReadOnlyCollection`1 addins, DirectoryPath installPath) in C:\projects\cake\src\Cake.Core\Scripting\ScriptProcessor.cs:line 106
>    at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 152
>    at Cake.Commands.DebugCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\DebugCommand.cs:line 50
>    at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
>    at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 74

I wonder if addressing the other two items would resolve my issue. I'm happy to log a separate issue for this if necessary.

**Comment by Jericho** [comment]
We performed a follow up automated audit of your Cake addin and found that some (or all) issues previously identified have not been resolved.

We strongly encourage you to make the modifications previously highlighted.



Apologies if this is already being worked on, or if there are existing open issues, this issue was created based on what is currently published for this package on NuGet.

This comment was created by a tool: Cake.AddinDiscoverer version 3.12.1

**Comment by zbeer** [comment]
All three items should now be addressed.  Thank you for the feedback!
